headhunter/core/urls.py
from django.urls import path

from core.views.add_resume_view import ResumeAddView, ResumeEditView, AddEducation, AddJob
from core.views.api_views import vacancy_list_view
from core.views.base import IndexView, update_resume
from core.views.resume_detail import ResumeDetailView, download_pdf
from core.views.vacancy import VacancyCreate, VacancyUpdate, VacancyDetail, vacancy_reload

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('add/resume', ResumeAddView.as_view(), name='add_resume'),
    path('edit/resume/<int:pk>', ResumeEditView.as_view(), name='edit_resume'),
    path('resume/<int:pk>/add_education', AddEducation.as_view(), name='add_education'),
    path('resume/<int:pk>/', ResumeDetailView.as_view(), name='resume_detail'),
    path('resume/<int:pk>/add_job', AddJob.as_view(), name='add_job'),
    path('resume/update/<int:pk>', update_resume, name='update'),
    path('resume/download/<int:pk>', download_pdf, name='download'),

    path('vacancy/create', VacancyCreate.as_view(), name='vacancy_create'),
    path('vacancy/update/<int:pk>', VacancyUpdate.as_view(), name='vacancy_update'),
    path('vacancy/<int:pk>', VacancyDetail.as_view(), name='vacancy_detail'),
    path('vacancy/reload/<int:pk>', vacancy_reload, name='reload'),

    path('api/vacancy', vacancy_list_view)
]

headhunter/headhunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include('accounts.urls')),
    path("", include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

headhunter/core/models.py
from django.db import models

from accounts.models import Profile

CATEGORY = (
    ('IT', 'IT'),
    ('DESIGN', 'Дизайн'),
    ('MANAGEMENT', 'Менеджмент'),
    ('MEDICINE', 'Медицина'),
    ('ENGINEERING', 'Инженерное дело'),
    ('ART', 'Искусство'),
    ('TRANSPORT', 'Транспорт'),
    ('MARKETING', 'Маркетинг'),
    ('TRADE', 'Торговля'),
    ('ECONOMY', 'Экономика')
)


class Resume(models.Model):
    category = models.TextField(verbose_name='Категория вакансии', choices=CATEGORY, null=True, blank=True)
    about = models.TextField(max_length=3000, verbose_name='О себе')
    salary = models.DecimalField(verbose_name='Желаемая зарплата', max_digits=10, decimal_places=2, null=True,
                                 blank=True)
    email = models.CharField(verbose_name='Email', max_length=100, null=True, blank=True)
    author = models.ForeignKey(Profile, verbose_name='Соискатель', on_delete=models.CASCADE)
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=20, null=True, blank=True)
    updated_at = models.DateTimeField(verbose_name='Последние изменение', auto_now_add=True)
    is_active = models.BooleanField(verbose_name='Скрыть резюме', default=False)
    telegram = models.CharField(verbose_name='Ссылка на телеграм', max_length=100, null=True, blank=True)
    linkedin = models.CharField(verbose_name='Ссылка на Linkedin', max_length=100, null=True, blank=True)
    facebook = models.CharField(verbose_name='Ссылка на Facebook', max_length=100, null=True, blank=True)

    def delete(self, using=None, keep_parents=False):
        self.is_active = True
        self.save()

    def __str__(self):
        return f'{self.author}'


class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    study = models.CharField(max_length=100, verbose_name='Место обучения')
    start_date = models.DateField(blank=True, null=True, verbose_name='Начал обучаться')
    end_date = models.DateField(blank=True, null=True, verbose_name='Закончил обучаться')


class Job(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, verbose_name='Обязанности')
    company = models.CharField(max_length=100, verbose_name='Название компании')
    start_date = models.DateField(blank=True, null=True, verbose_name='Начал работать')
    end_date = models.DateField(blank=True, null=True, verbose_name='Закончил работать')


class Vacancy(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название вакансии', null=False, blank=False)
    salary = models.DecimalField(verbose_name='Заработная плата', decimal_places=0, max_digits=10, null=False,
                                 blank=False)
    author = models.ForeignKey(Profile, related_name='company', verbose_name='Работодатель', on_delete=models.CASCADE)
    description = models.TextField(max_length=3000, verbose_name='Описание вакансии', null=False, blank=False)
    experience = models.FloatField(verbose_name='Опыт работы', null=False, blank=False)
    category = models.TextField(verbose_name='Категория вакансии', null=False, blank=False, choices=CATEGORY)
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')
    is_active = models.BooleanField(verbose_name='Скрыть вакансию', default=False)

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ['-updated_at']

headhunter/core/views/base.py
from urllib.parse import urlencode

from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView

from accounts.forms import CustomUserCreationForm, LoginForm
from accounts.models import Profile
from core.forms import SearchForm
from core.models import Resume, Vacancy
from django.core.paginator import Paginator


class IndexView(ListView):
    template_name = 'index.html'
    paginate_by = 3
    model = Vacancy
    context_object_name = 'vacancy'
    queryset = Vacancy.objects.filter(is_active=False).order_by('-updated_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['register_form'] = CustomUserCreationForm()
        context['login_form'] = LoginForm()
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value)
            queryset = queryset.filter(query)
        return queryset

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


def update_resume(request, *args, **kwargs):
    resume = get_object_or_404(Resume, pk=kwargs['pk'])
    resume.updated_at = timezone.now()
    resume.save()
    return redirect('employer_profile', pk=resume.author_id)


def vacancy_filter(request, pk):
    if pk == 1:
        vacancy = Vacancy.objects.filter(category='IT')
    return render(request, 'index.html', {'vacancy': vacancy})


class FilterIndexView(ListView):
    template_name = 'index.html'
    paginate_by = 20
    model = Vacancy
    context_object_name = 'vacancy'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['register_form'] = CustomUserCreationForm()
        context['login_form'] = LoginForm()
        return context

    def get_queryset(self):
        return Vacancy.objects.filter(is_active=False).order_by('-updated_at')

headhunter/core/views/resume_detail.py
import datetime

from django.template.loader import render_to_string
from weasyprint import HTML
import tempfile
from django.http import HttpResponse
from django.views.generic import DetailView

from accounts.models import Profile
from core.models import Resume, Education, Job


class ResumeDetailView(DetailView):
    model = Resume
    template_name = "resume_detail.html"
    context_object_name = 'resume'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # user = self.get_object()
        # resume = Resume.objects.filter(pk=self.object.pk)
        print(self.object.pk)
        context['education'] = Education.objects.filter(resume_id=self.object.pk)
        context['job'] = Job.objects.filter(resume_id=self.object.pk)
        return context


def download_pdf(request, *args, **kwargs):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename=Expenses' + \
                                      str(datetime.datetime.now()) + '.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    education = Education.objects.filter(resume_id=kwargs.get('pk'))
    job = Job.objects.filter(resume_id=kwargs.get('pk'))
    resume = Resume.objects.filter(pk=kwargs.get('pk'))
    to_str = resume.values('author')[0]
    check = to_str.get('author')
    author = Profile.objects.filter(pk=check)
    html_string = render_to_string('pdf_output.html',
                                   {'author': author, 'resume': resume, 'education': education, 'job': job})
    html = HTML(string=html_string, base_url=request.build_absolute_uri())
    result = html.write_pdf()
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(result)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())
    return response

headhunter/templates/applicant_profile.html
{% extends "base.html" %}
{% load static %}
{% block main_block %}
{% endblock %}

headhunter/templates/base.html
<!doctype html>
{% load static %}
{% load django_bootstrap5 %}

<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Headhunter</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <!--        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"-->
    <!--              integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">-->
    <!--     CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/price_rangs.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>

<body>
<!-- Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="https://upload.wikimedia.org/wikipedia/commons/7/79/HeadHunter_logo.png" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->

<header>
    <!-- Header Start -->
    <div class="header-area header-transparrent" style="background-color: #010b1d">
        <div class="headder-top header-sticky" style="background-color: #010b1d">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-3 col-md-2">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="{% url 'main' %}"><img
                                    src="https://upload.wikimedia.org/wikipedia/commons/7/79/HeadHunter_logo.png"
                                    style="width: 64px; height: 64px;" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-9 col-md-9">
                        <div class="menu-wrapper">
                            <!-- Main-menu -->
                            <div class="main-menu">
                                <nav class="d-none d-lg-block">
                                    <ul id="navigation">
                                        <li><a href="{% url 'main' %}" style="color: white">На главную</a></li>
                                        {% if user.is_authenticated %}
                                        <li><a href="{% url 'employer_profile' user.pk %}" style="color: white">Личный
                                            кабинет</a></li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>
                            <!-- Header-btn -->
                            <div class="header-btn d-none f-right d-lg-block">
                                {% if user.is_authenticated %}
                                <!--                                <b>Привет, {{ user.username }} </b>-->
                                <a class="btn head-btn1" href="{% url 'logout' %}">Выйти</a>
                                {% else %}
                                <button id="register_button" class="btn head-btn1">Register</button>
                                <button id="login_button" class="btn head-btn2">Login</button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>
<main>
    <div class="wrapper">
        {% block main_block %}
        {% endblock %}

    </div>
    {% block form %}
    {% endblock %}
    <div class="modals_block">
        {% block modal_block %}
        {% endblock %}
    </div>
</main>
<!--<footer style="position: absolute; left: 0; bottom: 0; width: 100%; height: 80px;">-->
<!--    <div class="footer-area footer-bg footer-padding">-->
<!--        <div class="container">-->
<!--            <div class="row d-flex justify-content-between">-->

<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</footer>-->


<!-- All JS Custom Plugins Link Here here -->
<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js'%}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js'%}"></script>
<script src="{% static 'assets/js/popper.min.js'%}"></script>
<script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'assets/js/jquery.slicknav.min.js'%}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/js/slick.min.js'%}"></script>
<script src="{% static 'assets/js/price_rangs.js'%}"></script>

<!-- One Page, Animated-HeadLin -->
<script src="{% static 'assets/js/wow.min.js'%}"></script>
<script src="{% static 'assets/js/animated.headline.js'%}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js'%}"></script>

<!-- Scrollup, nice-select, sticky -->
<script src="{% static 'assets/js/jquery.scrollUp.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.sticky.js'%}"></script>

<!-- contact js -->
<script src="{% static 'assets/js/contact.js'%}"></script>
<script src="{% static 'assets/js/jquery.form.js'%}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js'%}"></script>
<script src="{% static 'assets/js/mail-script.js'%}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js'%}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'assets/js/plugins.js'%}"></script>
<script src="{% static 'assets/js/main.js'%}"></script>
<script src="{% static 'main.js'%}"></script>
<script src="{% static 'liveSearch.js'%}"></script>
<!-- мой скрипт для форм выше -->
</body>
</html>

headhunter/templates/employer_profile.html
{% extends "base.html" %}
{% load static %}
{% block main_block %}
{% endblock %}

headhunter/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% block main_block %}
<div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="slider-active">
        <div class="single-slider slider-height d-flex align-items-center"
             data-background="{% static 'assets/img/hero/h1_hero.jpg'%}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-6 col-lg-9 col-md-10">
                        <div class="hero__caption">
                            <h1>Найди работу мечты</h1>
                        </div>
                    </div>
                </div>
                <!-- Search Box -->
                <div class="row">
                    <div class="col-xl-8">
                        {% include 'partial/search.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-4">
    <div class="vacancy_container">
        <h3 class="vacancies_title">
            Вакансии
        </h3>
        <div id="vacancies" class="vacancies_list_block">
            {% for v in vacancy %}
            <a href="{% url 'vacancy_detail' v.pk %}">
                <div class="card-body">
                    <h5 class="card-title">{{ v.name }}</h5>
                    <p>{{ v.category }}</p>
                    <p class="salary_text">{% load humanize %} {{ v.salary|intcomma }} KZT</p>
                    <p>Компания:
                        <a class="company_title" href="{% url 'employer_profile' v.author.pk %}">
                            {{ v.author.username }}
                        </a>
                    </p>
                    <p class="udated_vacancy mt-1">
                        Опубликовано: <span><b>{{ v.updated_at|date:"d-m-Y H:i" }}</b></span>
                    </p>
                </div>
            </a>
            {% endfor %}
        </div>
        {% include 'partial/pagination.html' %}
    </div>
</div>
{% endblock %}
{% block modal_block %}
<div id="registerModal" class="modal">
    <div class="modal-content"
         style="background-color: white; margin: 10% auto; padding: 20px; width: 80%; border: 1px solid#888">
        <div>
            <h4 class="register_title">Регистрация <span id="modalRegisterClose"
                                                         class="close">&times;</span>
            </h4>
            <form action="{% url 'register' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form">
                    {% bootstrap_form register_form %}
                    {% bootstrap_button button_type="submit" content='Зарегистрироваться' %}
                </div>
            </form>
        </div>
    </div>
</div>
<div id="loginModal" class="modal">
    <div class="modal-content"
         style="background-color: white; margin: 10% auto; padding: 20px; width: 80%; border: 1px solid#888">
        <div>
            <h5>Вход <span id="closeLogin" class="close">&times;</span></h5>
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <div class="form">
                    {% bootstrap_form login_form %}
                    {% bootstrap_button button_type="submit" content='Войти' %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

headhunter/templates/pdf_output.html
<!doctype html>
{% load static %}
{% load django_bootstrap5 %}

<!--<html class="no-js" lang="zxx">-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Headhunter</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/price_rangs.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"/>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<style>
    @page {
        size: "A4";
        margin: 2.5cm 1.5cm 3.5cm 1.5cm;
    }
</style>
<body>
<div class="job-post-company">
    <div class="container">
        <div class="row justify-content-between">
            <!-- Left Content -->
            <div class="col-xl-7 col-lg-8">
                <!-- job single -->
                <div class="single-job-items mb-50">
                    <div class="job-items">
                        {% for r in resume %}
                        {% for a in author %}
                        <div class="company-img company-img-details">
                            <img src="{{ a.avatar.url }}" style="width: 85px; height: 85px" alt="hello">
                        </div>
                        {% endfor %}
                        <div class="job-tittle">

                            <h4>{{ r.author.username }}</h4>

                            <ul>
                                <li>Категория {{ r.category }}</li>

                                <li>Желаемая зп {{ r.salary }}</li>
                            </ul>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <!-- job single End -->

                <div class="job-post-details">
                    <div class="post-details1 mb-50">
                        <!-- Small Section Tittle -->
                        {% for r in resume %}
                        <div class="small-section-tittle">
                            <h4>Обо мне</h4>
                        </div>
                        <p>{{ r.about }}</p>
                        {% endfor %}
                    </div>
                    <div class="post-details2  mb-50">
                        <!-- Small Section Tittle -->
                        <div class="small-section-tittle">
                            <h4>Образование и курсы</h4>
                        </div>
                        <ul>
                            {% for edu in education %}
                            <li>Место обучения: <b>{{ edu.study }}</b> <br>
                                В период с {{ edu.start_date }} по {{ edu.end_date }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="post-details2  mb-50">
                        <!-- Small Section Tittle -->
                        <div class="small-section-tittle">
                            <h4>Предыдущие места работы</h4>
                        </div>
                        <ul>
                            {% for j in job %}
                            <li>Название организации: <b>{{ j.company }}</b><br>
                                В период с {{ j.start_date }} по {{ j.end_date }}<br>
                                Обязанности: {{ j.description }}
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="post-details2  mb-50">
                        <!-- Small Section Tittle -->
                        <div class="small-section-tittle">
                            <h4>Контакты:</h4>
                        </div>
                        <ul>
                            {% for r in resume %}
                            <li>Telegram <b>{{ r.telegram }}</b></li>
                            <li>Linkedin <b>{{ r.linkedin }}</b></li>
                            <li>Facebook <b>{{ r.facebook }}</b></li>
                            <li>Email <b>{{ r.email }}</b></li>
                            <li>Телефон <b>{{ r.phone_number }}</b></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>


<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js'%}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js'%}"></script>
<script src="{% static 'assets/js/popper.min.js'%}"></script>
<script src="{% static 'assets/js/bootstrap.min.js'%}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'assets/js/jquery.slicknav.min.js'%}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'assets/js/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/js/slick.min.js'%}"></script>
<script src="{% static 'assets/js/price_rangs.js'%}"></script>

<!-- One Page, Animated-HeadLin -->
<script src="{% static 'assets/js/wow.min.js'%}"></script>
<script src="{% static 'assets/js/animated.headline.js'%}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js'%}"></script>

<!-- Scrollup, nice-select, sticky -->
<script src="{% static 'assets/js/jquery.scrollUp.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'assets/js/jquery.sticky.js'%}"></script>

<!-- contact js -->
<script src="{% static 'assets/js/contact.js'%}"></script>
<script src="{% static 'assets/js/jquery.form.js'%}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js'%}"></script>
<script src="{% static 'assets/js/mail-script.js'%}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js'%}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'assets/js/plugins.js'%}"></script>
<script src="{% static 'assets/js/main.js'%}"></script>
<script src="{% static 'main.js'%}"></script>
<!-- мой скрипт для форм выше -->
</body>
</html>

headhunter/templates/vacancy_detail.html
{% extends "base.html" %}
{% load static %}
{% block main_block %}
<div class="container">
    <div class="row">
        <div class="vacancy_block">
            <h3 class="mt-3 vacancy_title">Вакансия: <b>{{vacancy.name}}</b></h3>
            <p>Зарплата: <b>{{ vacancy.salary }} тг</b></p>
            <p>Описание вакансии: <b>{{ vacancy.description }} </b></p>
            <p>Требуемый опыт работы: <b>{{ vacancy.experience }} </b></p>
            <p>Категория вакансии: <b>{{ vacancy.get_category_display }} </b></p>
            <p class="reload_p">Обновлена: <b>{{ vacancy.updated_at|date:"d-m-Y H:i" }}</b>
                {% if user.is_authenticated %}
                {% if perms.core.change_vacancy or vacancy.author == request.user %}
                <a class="reload_btn" href="{% url 'reload' vacancy.pk %}">Обновить <i
                        class="fa-solid fa-rotate"></i></a>
                {% endif %}
                {% endif %}</p>
            {% if user.is_authenticated %}
            <div class="vacancy_link_block">
                {% if perms.core.change_vacancy or vacancy.author == request.user %}
                <a href="{% url 'vacancy_update' vacancy.pk %}" class="genric-btn primary circle">Редактировать</a>
                {% endif %}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}