headhunter/accounts/urls.py
from django.urls import path

from accounts.views import LoginView, logout_view, RegisterView, EmployerDetailView, UserChangeView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),
    path('profile/<int:pk>', EmployerDetailView.as_view(template_name='employer_profile.html'),
         name='employer_profile'),
    path('change_profile/<int:pk>', UserChangeView.as_view(), name='user_update'),

]

headhunter/core/urls.py
from django.urls import path

from core.views.add_resume_view import ResumeAddView, ResumeEditView, AddEducation, AddJob
from core.views.api_views import vacancy_list_view
from core.views.base import IndexView, update_resume
from core.views.resume_detail import ResumeDetailView, download_pdf
from core.views.vacancy import VacancyCreate, VacancyUpdate, VacancyDetail, vacancy_reload

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('add/resume', ResumeAddView.as_view(), name='add_resume'),
    path('edit/resume/<int:pk>', ResumeEditView.as_view(), name='edit_resume'),
    path('resume/<int:pk>/add_education', AddEducation.as_view(), name='add_education'),
    path('resume/<int:pk>/', ResumeDetailView.as_view(), name='resume_detail'),
    path('resume/<int:pk>/add_job', AddJob.as_view(), name='add_job'),
    path('resume/update/<int:pk>', update_resume, name='update'),
    path('resume/download/<int:pk>', download_pdf, name='download'),

    path('vacancy/create', VacancyCreate.as_view(), name='vacancy_create'),
    path('vacancy/update/<int:pk>', VacancyUpdate.as_view(), name='vacancy_update'),
    path('vacancy/<int:pk>', VacancyDetail.as_view(), name='vacancy_detail'),
    path('vacancy/reload/<int:pk>', vacancy_reload, name='reload'),

    path('api/vacancy', vacancy_list_view)
]

headhunter/headhunter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include('accounts.urls')),
    path("", include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

headhunter/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from accounts.managers import UserManager

ROLE = (('Employer', 'Работодатель'), ('Employee', 'Соискатель'))


class Profile(AbstractUser):
    email = models.EmailField(verbose_name='Электронная почта', unique=True, blank=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='avatars', verbose_name='Аватар',
                               default='/default_av.jpg')
    username = models.CharField(verbose_name='Имя пользователя', max_length=20, blank=True)
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=20, blank=True)
    user_role = models.TextField(verbose_name='Роль', choices=ROLE, null=False, blank=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return f'{self.email} {self.username}'

headhunter/core/models.py
from django.db import models

from accounts.models import Profile

CATEGORY = (
    ('IT', 'IT'),
    ('DESIGN', 'Дизайн'),
    ('MANAGEMENT', 'Менеджмент'),
    ('MEDICINE', 'Медицина'),
    ('ENGINEERING', 'Инженерное дело'),
    ('ART', 'Искусство'),
    ('TRANSPORT', 'Транспорт'),
    ('MARKETING', 'Маркетинг'),
    ('TRADE', 'Торговля'),
    ('ECONOMY', 'Экономика')
)


class Resume(models.Model):
    category = models.TextField(verbose_name='Категория вакансии', choices=CATEGORY, null=True, blank=True)
    about = models.TextField(max_length=3000, verbose_name='О себе')
    salary = models.DecimalField(verbose_name='Желаемая зарплата', max_digits=10, decimal_places=2, null=True,
                                 blank=True)
    email = models.CharField(verbose_name='Email', max_length=100, null=True, blank=True)
    author = models.ForeignKey(Profile, verbose_name='Соискатель', on_delete=models.CASCADE)
    phone_number = models.CharField(verbose_name='Номер телефона', max_length=20, null=True, blank=True)
    updated_at = models.DateTimeField(verbose_name='Последние изменение', auto_now_add=True)
    is_active = models.BooleanField(verbose_name='Скрыть резюме', default=False)
    telegram = models.CharField(verbose_name='Ссылка на телеграм', max_length=100, null=True, blank=True)
    linkedin = models.CharField(verbose_name='Ссылка на Linkedin', max_length=100, null=True, blank=True)
    facebook = models.CharField(verbose_name='Ссылка на Facebook', max_length=100, null=True, blank=True)

    def delete(self, using=None, keep_parents=False):
        self.is_active = True
        self.save()

    def __str__(self):
        return f'{self.author}'


class Education(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    study = models.CharField(max_length=100, verbose_name='Место обучения')
    start_date = models.DateField(blank=True, null=True, verbose_name='Начал обучаться')
    end_date = models.DateField(blank=True, null=True, verbose_name='Закончил обучаться')


class Job(models.Model):
    resume = models.ForeignKey(Resume, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, verbose_name='Обязанности')
    company = models.CharField(max_length=100, verbose_name='Название компании')
    start_date = models.DateField(blank=True, null=True, verbose_name='Начал работать')
    end_date = models.DateField(blank=True, null=True, verbose_name='Закончил работать')


class Vacancy(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название вакансии', null=False, blank=False)
    salary = models.DecimalField(verbose_name='Заработная плата', decimal_places=0, max_digits=10, null=False,
                                 blank=False)
    author = models.ForeignKey(Profile, related_name='company', verbose_name='Работодатель', on_delete=models.CASCADE)
    description = models.TextField(max_length=3000, verbose_name='Описание вакансии', null=False, blank=False)
    experience = models.FloatField(verbose_name='Опыт работы', null=False, blank=False)
    category = models.TextField(verbose_name='Категория вакансии', null=False, blank=False, choices=CATEGORY)
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')
    is_active = models.BooleanField(verbose_name='Скрыть вакансию', default=False)

    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'
        ordering = ['-updated_at']

headhunter/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

from accounts.models import ROLE


class LoginForm(forms.Form):
    email = forms.CharField(required=True, label='Логин')
    password = forms.CharField(required=True, label='Пароль', widget=forms.PasswordInput)


class CustomUserCreationForm(forms.ModelForm):
    username = forms.CharField(label='Имя', min_length=5, max_length=50,
                               widget=forms.TextInput(attrs={'placeholder': 'Имя', 'class': 'form-control'}))
    email = forms.CharField(label='Email', min_length=7, max_length=70, required=True,
                            widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control'}))
    avatar = forms.ImageField(label='Аватар', required=False)
    password = forms.CharField(label='Пароль', strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label='Подтвердите пароль', strip=False, required=True,
                                       widget=forms.PasswordInput)
    user_role = forms.ChoiceField(label='Роль', choices=ROLE,
                                  widget=forms.RadioSelect(attrs={'class': "choose_role_block"}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'avatar', 'password', 'password_confirm', 'phone_number', 'user_role')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')
        if password and password_confirm and password != password_confirm:
            raise ValidationError('Пароли не совпадают')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['email', 'phone_number', 'user_role', 'avatar']
        labels = {'email': 'Email', 'phone_number': 'Номер телефона', 'role': 'Роль', 'avatar': 'Аватар'}

headhunter/accounts/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView

from accounts.forms import LoginForm, CustomUserCreationForm, UserChangeForm
from accounts.models import Profile
from core.models import Resume, Vacancy


class LoginView(TemplateView):
    template_name = 'login.html'
    form = LoginForm

    def get(self, request, *args, **kwargs):
        form = self.form()
        context = {'form': form}
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        form = self.form(request.POST)
        if not form.is_valid():
            return redirect('main')
        password = form.cleaned_data.get('password')
        if '@' not in form.cleaned_data.get('email'):
            phone = form.cleaned_data.get('email')
            email = Profile.objects.filter(phone_number=phone).values('email')
            if len(email) == 0:
                return redirect('main')
            email_str = email[0]
            user = authenticate(request, email=email_str.get('email'), password=password)
            if not user:
                return redirect('main')
            login(request, user)
            return redirect('main')
        email = form.cleaned_data.get('email')
        user = authenticate(request, email=email, password=password)
        if not user:
            return redirect('main')
        login(request, user)
        return redirect('main')


def logout_view(request):
    logout(request)
    return redirect('main')


class RegisterView(TemplateView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
        return redirect('main')


class EmployerDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "employer_profile.html"
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['resumes'] = Resume.objects.filter(author=user).order_by('-updated_at')
        context['vacancy'] = Vacancy.objects.filter(author=user).order_by('-updated_at')
        context['change_form'] = UserChangeForm(instance=self.object)
        return context


class UserChangeView(UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'employer_profile.html'
    context_object_name = 'user_obj'

    def get_success_url(self):
        return reverse('employer_profile', kwargs={'pk': self.object.pk})

headhunter/accounts/templates/employer_profile.html
{% extends "base.html" %}
{% load static %}
{% block main_block %}
{% load django_bootstrap5 %}

<div class="container box_1170 mt-5 mb-200">
    <div class="row">
        <div class="col-md-3">
            <img src="{{ user_obj.avatar.url }}" alt="" class="rounded-circle img-fluid">
        </div>
        <div class="col-md-9 mt-sm-20">
            <div class="user_info">
                <p class="user_name">Логин: <b>{{ user_obj.username }}</b></p>
                <p class="user_mail">Email: <b>{{ user_obj.email }}</b></p>
                <p class="user_mail">Мобильный телефон: <b>{{ user_obj.phone_number }}</b></p>
                <p class="user_mail">Роль: <b>{{ user_obj.get_user_role_display }}</b></p>
                {% if user_obj.user_role == 'Employer' %}
                <a href="{% url 'vacancy_create' %}" class="genric-btn primary circle">Создать вакансию</a>
                {% else %}
                <a href="{% url 'add_resume' %}" class="genric-btn primary circle">Добавить резюме</a>
                {% endif %}
                <a href="#" id="register_button" class="genric-btn info circle">Редактировать профиль</a>
            </div>
        </div>
    </div>
    {% if user_obj.user_role == 'Employee' %}
    <div class="section-top-border mt-5">
        <h3 class="mb-30">Мои резюме</h3>
        <div class="row">
            {% for resume in resumes %}
            <div class="col-md-4 mt-3">
                <div class="single-defination">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{resume.category}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Желаемая зп {{resume.salary}}</h6>
                            <a href="{% url 'resume_detail' resume.pk %}"
                               class="genric-btn primary circle">Подробнее</a>
                            <a href="{% url 'update' resume.pk %}"
                               class="genric-btn primary circle">Обновить</a>
                            <a href="{% url 'download' resume.pk %}"
                               class="genric-btn primary circle">Скачать</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
    <div class="section-top-border mt-5">
        <h3 class="mb-30">Мои Вакансии</h3>
        <div class="row">
            {% for v in vacancy %}
            <div class="col-md-4 mt-3">
                <div class="single-defination">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">{{v.name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{v.get_category_display}}</h6>
                            <div class="btn__block">
                                <a href="{% url 'vacancy_detail' v.pk %}"
                                   class="genric-btn primary circle">Подробнее</a>
                                <a href="{% url 'vacancy_update' v.pk %}" class="genric-btn primary circle">Редактировать</a>
                            </div>
                            <p class="udated_vacancy">
                                Обновлено: <span>{{ v.updated_at }}</span>
                                <a class="reload_btn" href="{% url 'reload' v.pk %}">Обновить <i class="fa-solid fa-rotate"></i></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
</div>
<div id="registerModal" class="modal">
    <div class="modal-content"
         style="background-color: white; margin: 10% auto; padding: 20px; width: 80%; border: 1px solid#888">
        <div>
            <h4 class="register_title">Редактировать профиль<span id="modalRegisterClose"
                                                                  class="close">&times;</span>
            </h4>
            <form action="{% url 'user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% csrf_token %}
                {% bootstrap_form change_form %}
                {% bootstrap_button button_type="submit" content='Изменить' %}

            </form>
        </div>
    </div>
</div>

{% endblock %}